"""Vectorises selected Steam achievement icons of Skyrim SE into achievements.js.

    python achievements.py "<Steam>"        (default: C:\\Program Files (x86)\\Steam)

Needs `pip install pillow numpy scipy potracer`. Reads the achievement schema Steam caches in
appcache/stats, downloads the 64x64 icons from the Steam CDN and traces them with potrace:
white parts become var(--fg), the filled silhouette var(--bg) — same scheme as the map glyphs.
"""
import io, json, os, struct, sys, urllib.request
import numpy as np, potrace
from PIL import Image, ImageFilter
from scipy import ndimage

HERE = os.path.dirname(os.path.abspath(__file__))
APP = 489830
CDN = f'https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/{APP}/'
# English achievement name -> glyph name
WANTED = {
    'Solstheim Explorer': 'SolstheimExplorer',
}


def read_schema(path):
    """Steam binary KeyValues -> [(english name, icon file)]."""
    data, pos = open(path, 'rb').read(), 0

    def cstr():
        nonlocal pos
        end = data.index(b'\0', pos)
        s, pos = data[pos:end].decode('utf-8', 'replace'), end + 1
        return s

    def node():
        nonlocal pos
        d = {}
        while (t := data[pos]) != 8:
            pos += 1
            k = cstr()
            if t == 0: d[k] = node()
            elif t == 1: d[k] = cstr()
            elif t in (2, 3, 4, 6): d[k], pos = data[pos:pos + 4], pos + 4
            elif t == 7: d[k], pos = data[pos:pos + 8], pos + 8
            else: raise ValueError(f'KeyValues type {t}')
        pos += 1
        return d

    out = []

    def walk(n):
        if not isinstance(n, dict):
            return
        disp = n.get('display')
        if isinstance(disp, dict) and 'icon' in disp:
            name = disp.get('name', {})
            out.append((name.get('english') if isinstance(name, dict) else name, disp['icon']))
        for v in n.values():
            walk(v)

    walk(node())
    return out


def path_d(mask, scale):
    d = []
    for curve in potrace.Bitmap(~mask).trace(turdsize=20, alphamax=1.0, opticurve=True, opttolerance=0.2):
        p = curve.start_point
        d.append(f'M{p.x * scale:.2f} {p.y * scale:.2f}')
        for seg in curve.segments:
            e = seg.end_point
            if seg.is_corner:
                d.append(f'L{seg.c.x * scale:.2f} {seg.c.y * scale:.2f} L{e.x * scale:.2f} {e.y * scale:.2f}')
            else:
                d.append(f'C{seg.c1.x * scale:.2f} {seg.c1.y * scale:.2f} {seg.c2.x * scale:.2f} {seg.c2.y * scale:.2f} '
                         f'{e.x * scale:.2f} {e.y * scale:.2f}')
        d.append('Z')
    return ' '.join(d)


def trace(img, up=8):
    big = img.convert('L').resize((img.width * up, img.height * up), Image.LANCZOS) \
             .filter(ImageFilter.GaussianBlur(up * 0.35))
    g = np.array(big).astype(int)
    white = g > 215
    # Steam pads the icon with flat grey (~190); flood it in from the corners
    lab, _ = ndimage.label(np.abs(g - 190) < 28)
    outside = np.isin(lab, [l for l in {lab[0, 0], lab[0, -1], lab[-1, 0], lab[-1, -1]} if l])
    silhouette = ndimage.binary_fill_holes(ndimage.binary_opening(~outside, iterations=up // 2))
    s = 100 / big.width
    return {'w': 100, 'h': 100,
            'svg': f'<path style="fill:var(--bg)" d="{path_d(silhouette, s)}"/>'
                   f'<path style="fill:var(--fg)" d="{path_d(white & silhouette, s)}"/>'}


def main():
    steam = sys.argv[1] if len(sys.argv) > 1 else r'C:\Program Files (x86)\Steam'
    icons = dict(read_schema(os.path.join(steam, 'appcache', 'stats', f'UserGameStatsSchema_{APP}.bin')))
    glyphs = {}
    for ach, name in WANTED.items():
        with urllib.request.urlopen(CDN + icons[ach]) as r:
            glyphs[name] = trace(Image.open(io.BytesIO(r.read())))
    with open(os.path.join(HERE, 'achievements.js'), 'w', encoding='utf-8', newline='\n') as f:
        f.write('// Generated by achievements.py from Steam achievement icons. Do not edit.\n')
        f.write('const ACH_GLYPHS = {\n')
        f.write(',\n'.join(f'  {json.dumps(k)}: {json.dumps(v)}' for k, v in glyphs.items()))
        f.write('\n};\n')
    print(f'{len(glyphs)} glyphs -> achievements.js')


main()
